### ISSUE TITLE
Port log file handling code from alpenhorn1

### ISSUE THREAD

**Issue by ketiltrout** [radiocosmology/alpenhorn#161]
Alpenhorn-1 uses https://pypi.org/project/concurrent-log-handler/ to handle log files, which is very helpful for us on the clusters where we can't use logrotate to handle log files.

We should re-implement this as an optional feature, configured via the config file (instead of the `ALPENHORN_LOG_FILE` environmental variable).  e.g.:
```
logging:
    level: DEBUG
    file:
        name: ~/alpenspool/alpenhorn.log
        rotate: yes
        max-size: 4G
        file-count: 100
```
